let score=0,quizCredited=0;const scoreEl=document.getElementById('score'),quizScoreEl=document.getElementById('quizScore');function syncScore(){scoreEl.textContent=score;quizScoreEl.textContent=score;const p=document.getElementById('practiceScore');if(p)p.textContent=score}function addGoal(){if(score>=13)return;score++;syncScore();let p=document.createElement('div');p.className='goal-pop';p.textContent='ГОЛ! ⚽';document.body.appendChild(p);setTimeout(()=>p.remove(),900)}function mathTopicsUrl(){return '../../index.html';}function returnToTopics(){location.href=mathTopicsUrl();}
const vals=[2,3,4,5,6,7,10,15],good=new Set([2,3,5,6,10,15]),chips=document.getElementById('chips');let divisors30Done=false;vals.forEach(v=>{let b=document.createElement('button');b.className='chip';b.textContent=v;b.onclick=()=>{if(b.disabled)return;b.disabled=true;if(good.has(v)){b.classList.add('good')}else{b.style.background='#713c55';b.style.borderColor='#ff9870'};if([...good].every(x=>[...chips.children].some(z=>+z.textContent===x&&z.disabled))){let f=document.getElementById('fb');f.classList.remove('hidden');f.innerHTML='<b>Верные делители 30:</b> 2, 3, 5, 6, 10, 15.';if(!divisors30Done){addGoal();divisors30Done=true}}};chips.appendChild(b)});
let multDone=false;function checkMultiple(){let x=Number(document.getElementById('multInput').value),f=document.getElementById('multFb');if(x===35){f.textContent='Верно: прибавляем 7. Следующее кратное — 35.';if(!multDone){addGoal();multDone=true}}else f.textContent='Проверь шаг последовательности: каждое следующее число увеличивается на 7.'}
const vals24=[1,2,3,4,5,6,8,12,18,24],good24=new Set([1,2,3,4,6,8,12,24]);let picked24=new Set(),done24=false;const c24=document.getElementById('chips24');vals24.forEach(v=>{let b=document.createElement('button');b.className='chip';b.textContent=v;b.onclick=()=>{if(picked24.has(v))return;picked24.add(v);if(good24.has(v))b.classList.add('good');else{b.style.background='#713c55';b.style.borderColor='#ff9870'};if([...good24].every(x=>picked24.has(x))){document.getElementById('fb24').textContent='Все делители 24 найдены: 1, 2, 3, 4, 6, 8, 12, 24.';if(!done24){addGoal();done24=true}}};c24.appendChild(b)});
let relDone=false;function relation(btn,ok){if(ok){btn.classList.add('correct');document.getElementById('relFb').textContent='Верно: 40 : 8 = 5, поэтому 8 — делитель 40, а 40 — кратное 8.';if(!relDone){addGoal();relDone=true}}else{btn.classList.add('wrong');document.getElementById('relFb').textContent='Проверь делением: 40 : 8 делится без остатка.'}}
let teamDone=false;function teamCheck(btn,ok){if(ok){btn.classList.add('correct');document.getElementById('teamFb').textContent='Верно: 36 : 8 = 4 (остаток 4), значит разделить так без остатка нельзя.';if(!teamDone){addGoal();teamDone=true}}else{btn.classList.add('wrong');document.getElementById('teamFb').textContent='Попробуй разделить 36 на 8 и проверь остаток.'}}
let boardDone=false;function boardCheck(btn,ok){if(ok){btn.classList.add('correct');document.getElementById('boardFb').textContent='Верно: 24 делится и на 4, и на 6.';if(!boardDone){addGoal();boardDone=true}}else{btn.classList.add('wrong');document.getElementById('boardFb').textContent='Проверь по очереди делимость числа на 4 и на 6.'}}
const quizData=[{q:'1. Какое число является делителем 42?',a:['5','7','8','9'],c:1},{q:'2. Какое число кратно 9?',a:['32','40','45','52'],c:2},{q:'3. Выбери полный набор делителей 18.',a:['1, 2, 3, 6, 18','1, 2, 3, 6, 9, 18','2, 3, 6, 9','1, 3, 6, 9, 18'],c:1},{q:'4. Какое утверждение верно?',a:['6 — делитель 54','54 — делитель 6','7 — делитель 54','54 не кратно 6'],c:0},{q:'5. Найди следующее кратное: 12, 24, 36, 48, …',a:['50','54','60','62'],c:2},{q:'6. Какое число одновременно является делителем 24 и 36?',a:['8','12','18','24'],c:1},{q:'7. Найди число: оно больше 30, меньше 50 и кратно одновременно 6 и 8.',a:['36','40','48','42'],c:2}];let quizIndex=0,quizAnswers=Array(7).fill(null);function startTest(){quizIndex=0;document.getElementById('quizQuestionView').classList.remove('hidden');document.getElementById('quizResultView').classList.add('hidden');document.getElementById('quizScreen').classList.remove('hidden');renderQuiz()}function renderQuiz(){let x=quizData[quizIndex];document.getElementById('quizProgress').textContent='Вопрос '+(quizIndex+1)+' из 7';document.getElementById('quizQuestion').textContent=x.q;let b=document.getElementById('quizOptions');b.innerHTML='';x.a.forEach((t,i)=>{let z=document.createElement('button');z.className='quiz-option'+(quizAnswers[quizIndex]===i?' selected':'');z.textContent=t;z.onclick=()=>{quizAnswers[quizIndex]=i;renderQuiz()};b.appendChild(z)});document.getElementById('quizNext').textContent=quizIndex===6?'Проверить тест':'Следующий вопрос →';document.getElementById('quizWarn').classList.add('hidden')}function nextQuizQuestion(){if(quizAnswers[quizIndex]===null){document.getElementById('quizWarn').classList.remove('hidden');return}if(quizIndex<6){quizIndex++;renderQuiz()}else finishTest()}function saveBestTopic6(completed=false){const old=Math.max(0,Math.min(13,Number(localStorage.getItem('liga_math_topic6_goals')||0)||0));const best=Math.max(old,Math.min(13,score));localStorage.setItem('liga_math_topic6_goals',String(best));if(completed)localStorage.setItem('liga_math_topic6_complete','1');return best}function finishTest(){let correct=quizData.reduce((n,x,i)=>n+(quizAnswers[i]===x.c),0);for(let i=quizCredited;i<correct;i++)addGoal();quizCredited=Math.max(quizCredited,correct);let pct=Math.round(correct/7*100),best=saveBestTopic6(true);document.getElementById('quizQuestionView').classList.add('hidden');document.getElementById('quizResultView').classList.remove('hidden');document.getElementById('quizResult').innerHTML='<b>Мини-тест: '+correct+' из 7 ('+pct+'%).</b><br>За тест: '+correct+' ⚽<br><b>Всего за эту попытку: '+score+' ⚽ из 13</b><br>Лучший результат: '+best+' ⚽ из 13'}function finishLesson(){saveBestTopic6();location.replace(mathTopicsUrl())}syncScore();
function startPractice(){
  var s=document.getElementById('practiceScreen');
  if(s){s.classList.remove('hidden'); document.getElementById('practiceScore').textContent=score; s.scrollTop=0;}
}
function closePractice(){
  var s=document.getElementById('practiceScreen');
  if(s)s.classList.add('hidden');
  window.scrollTo({top:0,behavior:'smooth'});
}
