
(()=>{'use strict';const answers={K:3,M:5,O:6,E:7,F:9},letters=Object.keys(answers),bank=document.getElementById('mathRayBank'),track=document.getElementById('mathRayTrack'),status=document.getElementById('mathRayFeedback');const slots=new Map(),tiles=new Map();let selected=null,drag=null,suppressClick=false;const pos=n=>5+n*9.5;
for(let n=0;n<=9;n++){const tick=document.createElement('div');tick.className='math-ray-tick';tick.style.left=pos(n)+'%';track.append(tick);if(n<=1){const number=document.createElement('span');number.className='math-ray-num';number.style.left=pos(n)+'%';number.textContent=n;track.append(number)}else{const slot=document.createElement('button');slot.type='button';slot.className='math-ray-slot';slot.style.left=pos(n)+'%';slot.dataset.position=n;slot.setAttribute('aria-label','Деление '+n+', пусто');slot.addEventListener('click',()=>{if(selected)place(selected,n);else if(slot.dataset.letter)remove(slot.dataset.letter)});track.append(slot);slots.set(n,slot)}}
for(const letter of letters){const tile=document.createElement('button');tile.type='button';tile.className='math-ray-tile';tile.textContent=letter;tile.setAttribute('aria-label','Буква '+letter);tile.addEventListener('click',()=>{if(suppressClick){suppressClick=false;return}select(letter)});tile.addEventListener('pointerdown',e=>{if(tile.classList.contains('ray-placed'))return;drag={letter,x:e.clientX,y:e.clientY,active:false,ghost:null};tile.setPointerCapture(e.pointerId)});tile.addEventListener('pointermove',e=>{if(!drag||drag.letter!==letter)return;if(!drag.active&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>7){drag.active=true;drag.ghost=tile.cloneNode(true);drag.ghost.classList.add('math-ray-ghost');document.body.append(drag.ghost)}if(drag.ghost){drag.ghost.style.left=e.clientX-27+'px';drag.ghost.style.top=e.clientY-27+'px'}});tile.addEventListener('pointerup',e=>{if(!drag)return;const moved=drag.active;drag.ghost?.remove();drag=null;if(moved){suppressClick=true;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.math-ray-slot');if(target&&track.contains(target))place(letter,Number(target.dataset.position));setTimeout(()=>suppressClick=false,0)}});tile.addEventListener('pointercancel',()=>{drag?.ghost?.remove();drag=null});bank.append(tile);tiles.set(letter,tile)}
function select(letter){if(tiles.get(letter).classList.contains('ray-placed'))return;selected=selected===letter?null:letter;tiles.forEach((tile,l)=>tile.classList.toggle('ray-selected',selected===l))}
function clearSlot(slot){delete slot.dataset.letter;slot.textContent='';slot.className='math-ray-slot';slot.setAttribute('aria-label','Деление '+slot.dataset.position+', пусто')}
function remove(letter){for(const slot of slots.values())if(slot.dataset.letter===letter)clearSlot(slot);tiles.get(letter).classList.remove('ray-placed');status.textContent='';select(letter)}
function place(letter,n){if(!slots.has(n))return;for(const slot of slots.values())if(slot.dataset.letter===letter)clearSlot(slot);const slot=slots.get(n);if(slot.dataset.letter&&slot.dataset.letter!==letter)tiles.get(slot.dataset.letter).classList.remove('ray-placed');slot.dataset.letter=letter;slot.textContent=letter;slot.className='math-ray-slot ray-filled';slot.setAttribute('aria-label','Деление '+n+', буква '+letter);tiles.get(letter).classList.add('ray-placed');selected=null;tiles.forEach(t=>t.classList.remove('ray-selected'));status.textContent='Буква '+letter+' поставлена. Нажми на неё на луче, чтобы вернуть.'}
document.getElementById('mathRayCheck')?.addEventListener('click',()=>{let placed=0,correct=0;for(const [n,slot] of slots){slot.classList.remove('ray-correct','ray-wrong');if(slot.dataset.letter){placed++;const ok=answers[slot.dataset.letter]===n;correct+=Number(ok);slot.classList.add(ok?'ray-correct':'ray-wrong')}}recordRayFirstGoal('letters',placed===5&&correct===5);status.textContent=placed<5?`Размещено ${placed} из 5. Верно: ${correct}. Расставь остальные буквы.`:correct===5?'Гол! Все пять точек стоят верно.':'Верно: '+correct+' из 5. Переставь красные точки и проверь снова.'});
document.getElementById('mathRayReset')?.addEventListener('click',()=>{for(const slot of slots.values())clearSlot(slot);tiles.forEach(tile=>tile.classList.remove('ray-placed','ray-selected'));selected=null;status.textContent='Начни с отметок 0 и 1.'});
})();
