
(()=>{
const blocks=[{"key":"A","name":"Базовая точность","desc":"Запись чисел, разряды и координаты","tasks":[{"id":"A1","prompt":"Запиши цифрами число: сорок два миллиона семь тысяч девять.","answer":"42007009","explain":"42 миллиона + 7 тысяч + 9 = 42 007 009."},{"id":"A2","prompt":"Каково разрядное значение цифры 7 в числе 507 324 618?","answer":"7000000","explain":"Цифра 7 находится в разряде миллионов: 7 000 000."},{"id":"A3","prompt":"На числовом луче отмечена точка A. Введи её координату.","answer":"6","explain":"Единичный отрезок — расстояние между соседними отметками. От 0 до A шесть таких отрезков.","ray":true},{"id":"A4","prompt":"Найди наименьшую цифру x, при которой число 38x4 делится на 3.","answer":"0","explain":"Сумма цифр равна 15 + x. Наименьшее подходящее значение x — 0."}]},{"key":"Б","name":"Применяем правила","desc":"Сравнение, луч и признаки делимости","tasks":[{"id":"B1","prompt":"Какое натуральное число находится строго между 62 000 094 и 62 000 096?","answer":"62000095","explain":"Соседнее число между ними — 62 000 095."},{"id":"B2","prompt":"Единичный отрезок числового луча равен четырём клеткам. Сколько клеток от начала луча до точки с координатой 7?","answer":"28","explain":"Семь единичных отрезков по четыре клетки: 7 · 4 = 28."},{"id":"B3","prompt":"Найди наименьшее трёхзначное число, которое делится и на 4, и на 9.","answer":"108","explain":"Число должно делиться на 36. Первое трёхзначное кратное 36 — 108."},{"id":"B4","prompt":"Сколько существует двузначных чисел, у которых цифра десятков на 3 больше цифры единиц?","answer":"7","explain":"Это числа 30, 41, 52, 63, 74, 85 и 96."}]},{"key":"В","name":"Задачи на рассуждение","desc":"Условия на цифры и подсчёт вариантов","tasks":[{"id":"C1","prompt":"Запиши наибольшее семизначное число с различными цифрами, которое делится на 5.","answer":"9876540","explain":"При наибольших цифрах слева последняя цифра должна быть 0: 9 876 540."},{"id":"C2","prompt":"Сколько четырёхзначных чисел с цифрами в строго возрастающем порядке делится на 5?","answer":"4","explain":"Последняя цифра — 5. Остальные три выбираются из 1, 2, 3, 4: всего 4 способа."},{"id":"C3","prompt":"Найди наименьшее число вида 7a3b, которое делится одновременно на 4 и на 9. Буквы a и b обозначают цифры.","answer":"7236","explain":"Последние две цифры — 32 или 36. Условию делимости на 9 отвечают 7632 и 7236; меньшее — 7236."},{"id":"C4","prompt":"Для нумерации страниц от 1 до последней использовали 264 цифры. Сколько страниц в книге?","answer":"124","explain":"Страницы 1–9 дают 9 цифр, 10–99 — 180. Остаётся 75 цифр, то есть ещё 25 трёхзначных страниц: последняя — 124."}]}];
const $cw=id=>document.getElementById(id);
const storeKey='liga-control-math-k1-v1';
const ray='<svg class="cw-ray" viewBox="0 0 590 100" role="img" aria-label="Числовой луч от нуля до восьми, точка A на шестой отметке"><path d="M35 51H547" fill="none" stroke="#174b80" stroke-width="4"/><path d="m547 51-13-8m13 8-13 8" fill="none" stroke="#174b80" stroke-width="4"/>'+Array.from({length:9},(_,i)=>`<path d="M${40+i*60} 41v20" stroke="#174b80" stroke-width="3"/>`).join('')+'<text x="34" y="86" font-size="22" fill="#173c69">0</text><text x="94" y="86" font-size="22" fill="#173c69">1</text><circle cx="400" cy="51" r="7" fill="#ec8522"/><text x="393" y="34" font-size="23" font-weight="bold" fill="#8e4919">A</text></svg>';
let submitted=null;
try{const raw=JSON.parse(localStorage.getItem(storeKey)||'null');if(raw?.complete&&raw.answers&&typeof raw.answers==='object')submitted=raw}catch{}
function switchBlock(index){document.querySelectorAll('#cwTabs .cw-tab').forEach((x,i)=>x.classList.toggle('active',i===index));document.querySelectorAll('#cwTasks .cw-pane').forEach((x,i)=>x.classList.toggle('active',i===index))}
function normalise(value){const n=value.trim().replace(/[\s\u00a0\u202f]/g,'').replace(/^\+/,'');if(!/^-?\d+$/.test(n))return null;return BigInt(n).toString()}
blocks.forEach((block,bi)=>{
 const tab=document.createElement('button');tab.type='button';tab.className='cw-tab'+(bi===0?' active':'');tab.textContent=`Блок ${block.key} · ${block.name}`;tab.onclick=()=>switchBlock(bi);$cw('cwTabs').append(tab);
 const pane=document.createElement('div');pane.className='cw-pane'+(bi===0?' active':'');const title=document.createElement('h2');title.textContent=`Блок ${block.key} · ${block.name}`;pane.append(title);const desc=document.createElement('p');desc.textContent=block.desc;pane.append(desc);
 block.tasks.forEach((task,i)=>{const article=document.createElement('article');article.className='cw-task';article.dataset.taskId=task.id;const label=document.createElement('label');label.htmlFor='cw'+task.id;const number=document.createElement('span');number.className='cw-num';number.textContent=`${i+1}.`;label.append(number,document.createTextNode(task.prompt));article.append(label);if(task.ray){const figure=document.createElement('div');figure.innerHTML=ray;article.append(figure.firstElementChild)}const input=document.createElement('input');input.id='cw'+task.id;input.type='text';input.inputMode='numeric';input.autocomplete='off';input.placeholder='Впиши число';input.setAttribute('aria-label',`${block.key}${i+1}: ${task.prompt}`);const feed=document.createElement('div');feed.className='cw-feedback';feed.hidden=true;article.append(input,feed);pane.append(article)});$cw('cwTasks').append(pane)
});
function displayResult(answers){let total=0;const details=[];blocks.forEach(b=>{let earned=0;b.tasks.forEach(task=>{const input=$cw('cw'+task.id);input.value=answers[task.id]??'';input.disabled=true;const article=input.closest('.cw-task');const good=normalise(input.value)===task.answer;article.classList.toggle('correct',good);article.classList.toggle('wrong',!good);const feed=article.querySelector('.cw-feedback');feed.hidden=false;feed.textContent=(good?'Верно. ':'Неверно. Правильный ответ: '+Number(task.answer).toLocaleString('ru-RU')+'. ')+task.explain;earned+=Number(good)});total+=earned;details.push(`Блок ${b.key}: ${earned} / ${b.tasks.length}`)});const result=$cw('cwResult');result.replaceChildren();const strong=document.createElement('strong');strong.textContent=`Результат: ${total} из 12`;const note=document.createElement('p');note.textContent='Работа отправлена. Верные ответы и пояснения показаны под заданиями каждого блока.';result.append(strong,note);details.forEach(text=>{const span=document.createElement('span');span.textContent=text;result.append(span)});result.classList.remove('hidden');$cw('cwCheck').classList.add('hidden');$cw('cwNotice').textContent='Результат сохранён на этом устройстве.';$cw('mathControlSaved').textContent=`Результат контрольной: ${total} / 12`}
if(submitted)displayResult(submitted.answers);
$cw('startMathControl').onclick=()=>{show('mathControlTest');if(submitted)displayResult(submitted.answers)};
$cw('mathControlTestBack').onclick=()=>show('mathControlWorks');
$cw('cwCheck').onclick=()=>{if(submitted)return;const answers={};for(let bi=0;bi<blocks.length;bi++){for(const task of blocks[bi].tasks){const input=$cw('cw'+task.id),normalized=normalise(input.value);if(normalized===null){$cw('cwNotice').textContent='Заполни все поля числами, затем отправь работу.';switchBlock(bi);input.focus();return}answers[task.id]=input.value}}submitted={complete:true,answers};try{localStorage.setItem(storeKey,JSON.stringify(submitted))}catch{}displayResult(answers);$cw('cwResult').scrollIntoView({behavior:'smooth',block:'center'})};
})();
